# Generated by Django 3.2.12 on 2023-04-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='url',
            field=models.TextField(),
        ),
    ]
