# Generated by Django 3.2.12 on 2023-04-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_apidata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='impact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='insight',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='pestle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='relevance',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
